# Generated by Django 4.2.2 on 2023-06-24 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brain_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
